### ISSUE TITLE
Bug: Clustal = False within "pre_thread.py"

### ISSUE THREAD

**Issue by pstumps** [snerligit/mhc-pep-threader#1]
If clustal=False under "pre_thread.py" for function align_template_target_sequences, peptide sequences within the MHC groove of generated PDBS will be cut off. 

Printing self.template.get_sequence() and self.target.get_sequence(key) will give the full protein sequence including peptide. However, after running them through self.alignment.align(), printing self.alignment.get_aligned_query() and self.alignment.get_aligned_target() generates a cut off peptide. 

This may be due to the use of the StripedSmithWaterman function.

**Comment by snerligit** [comment]
Removed support for SmithWaterman. Now supporting only clustalomega
